
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elvirayu
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2() {
        initComponents();
        selectData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        panel2 = new java.awt.Panel();
        label2 = new java.awt.Label();
        nama = new java.awt.Label();
        staTuju = new java.awt.Label();
        staAwal = new java.awt.Label();
        tanggalB = new java.awt.Label();
        jenKer = new java.awt.Label();
        waBer = new java.awt.Label();
        temDu = new java.awt.Label();
        hrga = new java.awt.Label();
        sa = new javax.swing.JComboBox<>();
        tp2 = new javax.swing.JComboBox<>();
        st = new javax.swing.JComboBox<>();
        tp1 = new javax.swing.JComboBox<>();
        panel3 = new java.awt.Panel();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        h = new javax.swing.JTextField();
        nm1 = new javax.swing.JTextField();
        jk = new javax.swing.JTextField();
        wb = new javax.swing.JTextField();
        tp3 = new javax.swing.JComboBox<>();
        tb = new com.toedter.calendar.JDateChooser();
        panel4 = new java.awt.Panel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel5.setText("STASIUN KERETA API");
        jLabel5.setToolTipText("");
        panel1.add(jLabel5);
        jLabel5.setBounds(390, 30, 230, 30);

        jLabel8.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        jLabel8.setText("Jl. P. Antasari, Kampungdalem, Kec. Tulungagung");
        panel1.add(jLabel8);
        jLabel8.setBounds(280, 70, 430, 20);

        label1.setFont(new java.awt.Font("Traditional Arabic", 1, 18)); // NOI18N
        label1.setText("Kabupaten Tulungagung, Jawa Timur 66212, Indonesia");
        panel1.add(label1);
        label1.setBounds(280, 90, 440, 20);

        panel2.setBackground(new java.awt.Color(153, 153, 255));
        panel2.setLayout(null);

        label2.setFont(new java.awt.Font("DokChampa", 1, 18)); // NOI18N
        label2.setText("Data Pemesan");
        panel2.add(label2);
        label2.setBounds(440, 20, 130, 22);

        nama.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        nama.setText("Nama Pemesan");
        panel2.add(nama);
        nama.setBounds(20, 50, 106, 20);

        staTuju.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        staTuju.setText("Stasiun Tujuan");
        panel2.add(staTuju);
        staTuju.setBounds(20, 130, 100, 20);

        staAwal.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        staAwal.setText("Stasiun Awal");
        panel2.add(staAwal);
        staAwal.setBounds(20, 90, 90, 20);

        tanggalB.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        tanggalB.setText("Tanggal Berangkat");
        panel2.add(tanggalB);
        tanggalB.setBounds(470, 50, 140, 20);

        jenKer.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        jenKer.setText("Jenis Kereta");
        panel2.add(jenKer);
        jenKer.setBounds(20, 170, 100, 20);

        waBer.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        waBer.setText("Waktu Berangkat");
        panel2.add(waBer);
        waBer.setBounds(470, 90, 120, 20);

        temDu.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        temDu.setText("Tempat Duduk");
        panel2.add(temDu);
        temDu.setBounds(470, 130, 120, 20);

        hrga.setFont(new java.awt.Font("DokChampa", 1, 12)); // NOI18N
        hrga.setText("Harga");
        panel2.add(hrga);
        hrga.setBounds(470, 170, 60, 20);

        sa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stasiun Tulungagung", "Stasiun Surabaya", "Stasiun Malang", "Stasiun Jakarta", "Stasiun Bandung", "Stasiun Jogja" }));
        panel2.add(sa);
        sa.setBounds(130, 90, 300, 30);

        tp2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E" }));
        panel2.add(tp2);
        tp2.setBounds(770, 130, 70, 30);

        st.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stasiun Tulungagung", "Stasiun Surabaya", "Stasiun Malang", "Stasiun Jakarta", "Stasiun Bandung", "Stasiun Jogja" }));
        panel2.add(st);
        st.setBounds(130, 130, 300, 30);

        tp1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerbong 1", "Gerbong 2", "Gerbong 3", "Gerbong 4", "Gerbong 5" }));
        panel2.add(tp1);
        tp1.setBounds(630, 130, 110, 30);

        panel3.setBackground(new java.awt.Color(153, 153, 255));
        panel3.setLayout(null);

        btnSave.setBackground(new java.awt.Color(255, 153, 153));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        panel3.add(btnSave);
        btnSave.setBounds(40, 10, 80, 23);

        btnClear.setBackground(new java.awt.Color(255, 153, 153));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        panel3.add(btnClear);
        btnClear.setBounds(130, 10, 70, 23);

        btnDel.setBackground(new java.awt.Color(255, 153, 153));
        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        panel3.add(btnDel);
        btnDel.setBounds(210, 10, 73, 23);

        btnPrint.setBackground(new java.awt.Color(255, 153, 153));
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        panel3.add(btnPrint);
        btnPrint.setBounds(300, 10, 70, 23);

        panel2.add(panel3);
        panel3.setBounds(610, 0, 400, 40);
        panel2.add(h);
        h.setBounds(630, 170, 300, 30);
        panel2.add(nm1);
        nm1.setBounds(130, 50, 300, 30);
        panel2.add(jk);
        jk.setBounds(130, 170, 300, 30);
        panel2.add(wb);
        wb.setBounds(630, 90, 300, 30);

        tp3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22" }));
        tp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tp3ActionPerformed(evt);
            }
        });
        panel2.add(tp3);
        tp3.setBounds(860, 130, 70, 30);
        panel2.add(tb);
        tb.setBounds(630, 50, 300, 30);

        panel1.add(panel2);
        panel2.setBounds(20, 250, 1000, 250);

        panel4.setBackground(new java.awt.Color(153, 153, 255));
        panel4.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NoID", "NamaPemesan", "StasiunAwal", "StasiunTujuan", "TanggalBerangkat", "JenisKereta", "WaktuBerangkat", "TempatDuduk", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
            jTable1.getColumnModel().getColumn(6).setResizable(false);
            jTable1.getColumnModel().getColumn(7).setResizable(false);
            jTable1.getColumnModel().getColumn(8).setResizable(false);
        }

        panel4.add(jScrollPane1);
        jScrollPane1.setBounds(0, 20, 1000, 240);

        panel1.add(panel4);
        panel4.setBounds(20, 500, 1000, 290);

        jLabel9.setIcon(new javax.swing.ImageIcon("F:\\Logo Kereta Api baru cdr.png")); // NOI18N
        jLabel9.setText("jLabel9");
        panel1.add(jLabel9);
        jLabel9.setBounds(710, 20, 310, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon("F:\\1912061_10152307402461253_1881241236_o.png")); // NOI18N
        panel1.add(jLabel11);
        jLabel11.setBounds(30, 10, 200, 200);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 1040, 800);

        setSize(new java.awt.Dimension(1054, 844));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormata = new SimpleDateFormat("yyyy-MM-dd");
        String tanggal = dateFormata.format(tb.getDate());
        String awal = sa.getSelectedItem().toString();
        String tujuan = st.getSelectedItem().toString();
        String duduk = tp1.getSelectedItem().toString() + tp2.getSelectedItem().toString() + tp3.getSelectedItem().toString();
       
        if ("".equals(nm1.getText()) || "".equals(h.getText()) || "".equals(jk.getText())||"".equals(wb.getText())||"".equals(tanggal)){
        
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);
        }
        
        else 
        {
           
            String SQL="INSERT INTO form " 
                    + "VALUES ('"+nm1.getText()+"',NULL,'"+awal+"','"+tujuan+"','"+tanggal+"','"+jk.getText()+"','"+wb.getText()+"','"+duduk+"',"+h.getText()+")";
            System.out.println(SQL);
            int status = KoneksiDB.execute(SQL);
            if(status == 1)
            {
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan","Sukses", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan","Gagal", JOptionPane.WARNING_MESSAGE);
            }
        } 
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
         MessageFormat header = new MessageFormat("Transaksi Tiket Kereta Api Stasiun Tulungagung");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}");
        try {
           jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }

    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:
        int baris = jTable1.getSelectedRow();
        if (baris != 1) {
            String NoID = jTable1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM form WHERE NoID='"+NoID+"'";
            int status = KoneksiDB.execute(SQL);
            
            if(status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus","Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal dihapus","Gagal", JOptionPane.WARNING_MESSAGE);
            }    
        }
        
        else {
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih Dahulu","Error", JOptionPane.WARNING_MESSAGE);
        }                      
        
        selectData();
        
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        nm1.setText("");
        jk.setText("");
        wb.setText("");
        tb.setDate(null);
        h.setText("");
        sa.setSelectedItem("Stasiun Tulungagung");
        st.setSelectedItem("Stasiun Tulungagung");
        tp1.setSelectedItem("Gerbong 1");
        tp2.setSelectedItem("A");
        tp3.setSelectedItem("1");
        
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void tp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tp3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tp3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField h;
    private java.awt.Label hrga;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Label jenKer;
    private javax.swing.JTextField jk;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label nama;
    private javax.swing.JTextField nm1;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel4;
    private javax.swing.JComboBox<String> sa;
    private javax.swing.JComboBox<String> st;
    private java.awt.Label staAwal;
    private java.awt.Label staTuju;
    private java.awt.Label tanggalB;
    private com.toedter.calendar.JDateChooser tb;
    private java.awt.Label temDu;
    private javax.swing.JComboBox<String> tp1;
    private javax.swing.JComboBox<String> tp2;
    private javax.swing.JComboBox<String> tp3;
    private java.awt.Label waBer;
    private javax.swing.JTextField wb;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NoID","Nama Pemesan","Stasiun Awal","Stasiun Tujuan","Tanggal Berangkat","Jenis Kereta","Waktu Berangkat","Tempat Duduk","Harga"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM form";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try {
            while(rs.next()) {
                String NID = rs.getString(2);
                String Nama = rs.getString(1);
                String SAA=rs.getString(3);
                String STT=rs.getString(4);
                String TBB = rs.getString(5);
                String JKK = rs.getString(6);
                String WBB = rs.getString(7);
                String TDD = rs.getString(8);
                String HRR = rs.getString(9);
           String data[]={NID,Nama,SAA,STT,TBB,JKK,WBB,TDD,HRR};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Frame2.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(dtm);
    }
}
